PRESETS = {
    "youtube_1080p_mp4": {
        "label": "YouTube 1080p",
        "extension": ".mp4",
        "video_codec": "libx264",
        "audio_codec": "aac",
        "width": 1920,
        "height": 1080,
        "fps": 30,
        "video_bitrate": "8M",
        "audio_bitrate": "192k",
        "pixel_format": "yuv420p",
        "flags": ["+faststart"],
    },
    "youtube_4k_mp4": {
        "label": "YouTube 4K",
        "extension": ".mp4",
        "video_codec": "libx264",
        "audio_codec": "aac",
        "width": 3840,
        "height": 2160,
        "fps": 30,
        "video_bitrate": "45M",
        "audio_bitrate": "192k",
        "pixel_format": "yuv420p",
        "flags": ["+faststart"],
    },
    "shorts_1080x1920": {
        "label": "YouTube Shorts 1080x1920",
        "extension": ".mp4",
        "video_codec": "libx264",
        "audio_codec": "aac",
        "width": 1080,
        "height": 1920,
        "fps": 30,
        "video_bitrate": "6M",
        "audio_bitrate": "128k",
        "pixel_format": "yuv420p",
    },
    "tiktok_1080x1920": {
        "label": "TikTok 1080x1920",
        "extension": ".mp4",
        "video_codec": "libx264",
        "audio_codec": "aac",
        "width": 1080,
        "height": 1920,
        "fps": 30,
        "video_bitrate": "5M",
        "audio_bitrate": "128k",
        "pixel_format": "yuv420p",
    },
    "instagram_square_1080": {
        "label": "Instagram Square 1080x1080",
        "extension": ".mp4",
        "video_codec": "libx264",
        "audio_codec": "aac",
        "width": 1080,
        "height": 1080,
        "fps": 30,
        "video_bitrate": "6M",
        "audio_bitrate": "128k",
        "pixel_format": "yuv420p",
    },
    "web_720p": {
        "label": "Web 720p",
        "extension": ".mp4",
        "video_codec": "libx264",
        "audio_codec": "aac",
        "width": 1280,
        "height": 720,
        "fps": 30,
        "video_bitrate": "4M",
        "audio_bitrate": "128k",
        "pixel_format": "yuv420p",
    },
    "archive_lossless": {
        "label": "Archive Lossless (MKV)",
        "extension": ".mkv",
        "video_codec": "libx264rgb",
        "audio_codec": "pcm_s16le",
        "width": None,
        "height": None,
        "fps": None,
        "video_bitrate": None,
        "audio_bitrate": None,
        "pixel_format": "yuv444p",
    },
    "audio_wav": {
        "label": "Audio WAV",
        "extension": ".wav",
        "video_codec": None,
        "audio_codec": "pcm_s16le",
        "width": 0,
        "height": 0,
        "fps": None,
        "video_bitrate": None,
        "audio_bitrate": None,
        "pixel_format": None,
        "audio_only": True,
    },
    "audio_mp3": {
        "label": "Audio MP3",
        "extension": ".mp3",
        "video_codec": None,
        "audio_codec": "libmp3lame",
        "width": 0,
        "height": 0,
        "fps": None,
        "video_bitrate": None,
        "audio_bitrate": "192k",
        "pixel_format": None,
        "audio_only": True,
    },
    "gif_preview": {
        "label": "GIF Preview",
        "extension": ".gif",
        "video_codec": "gif",
        "audio_codec": None,
        "width": 640,
        "height": None,
        "fps": 10,
        "video_bitrate": None,
        "audio_bitrate": None,
        "pixel_format": "palettegen+paletteuse",
    },
}
