/**
 * SCDL Emit Packet Pass
 *
 * Assembles the final PixelBrainAssetPacket from the expanded AST.
 * Calls into the existing createPixelBrainAssetPacket() from pixelbrain-asset-packet.js.
 */

import {
  createPixelBrainAssetPacket,
  normalizePixelBrainCanvas,
} from '../../pixelbrain-asset-packet.js';

/**
 * @param {object} ast - Fully expanded SCDL AST
 * @param {import('../scdl.errors.js').SCDLError[]} _errors
 * @returns {import('../../pixelbrain-asset-packet.js').PixelBrainAssetPacket}
 */
export function emitPacketPass(ast, _errors) {
  const canvas = normalizePixelBrainCanvas(ast.canvas);

  // Flatten all coordinates from all parts
  const allCoordinates = [];
  const allNoise = [];

  for (const part of ast.parts) {
    for (const coord of (part.coordinates || [])) {
      allCoordinates.push({
        x:        coord.x,
        y:        coord.y,
        color:    coord.color,
        partId:   coord.partId || part.id,
        material: coord.material || part.material,
        role:     coord.role,
        _fillIntent: coord._fillIntent || false,
      });
    }
    for (const noise of (part.noiseDescriptors || [])) {
      allNoise.push(noise);
    }
  }

  // Build palette entries from AST palette
  const paletteColors = Object.values(ast.palette || {}).filter(Boolean);
  const sourcePalette = paletteColors.length
    ? [{ key: 'scdl-source', colors: paletteColors, source: 'scdl', weights: [] }]
    : [];

  // Build part metadata tags
  const partTags = (ast.parts || []).map(p => `${p.id}:${p.material}`);

  const packet = createPixelBrainAssetPacket({
    id:      null, // stableId generated by packet factory
    canvas,
    geometry: {
      mode:        'coordinates',
      coordinates: allCoordinates,
    },
    palette: {
      sourcePalette,
      authority: 'scdl.emit-packet.v1',
    },
    source: {
      kind:  'scdl',
      id:    ast.asset,
      label: `SCDL:${ast.asset}`,
    },
    material: {
      id: _primaryMaterial(ast.parts),
    },
    noiseDescriptors: allNoise,
    provenance: {
      createdBy:  'scdl-compiler.v1',
      operations: [
        { op: 'parse',          checksum: ast.checksum },
        { op: 'compile',        partCount: ast.parts.length },
        { op: 'coordinates',    count: allCoordinates.length },
      ],
    },
    metadata: {
      tags:  ['scdl', ast.type, ...partTags],
      notes: [
        `SCDL asset: ${ast.asset}`,
        `Canvas: ${canvas.width}x${canvas.height}`,
        `Parts: ${ast.parts.map(p => p.id).join(', ')}`,
        ast.parts.some(p => p.intentOps?.length) ? 'Contains trace intents (runtime resolution)' : null,
      ].filter(Boolean),
    },
  });

  return packet;
}

function _primaryMaterial(parts) {
  if (!parts || parts.length === 0) return 'source';
  return parts[0].material || 'source';
}
