

_SEVERITY_ICON = {"CRIT": "!!", "WARN": "!", "INFO": "i"}


def render_markdown(critique, references=None):
    sections = {}

    sections["verdict"] = _render_verdict(critique)
    sections["scorecard"] = _render_scorecard(critique)
    sections["flags"] = _render_flags(critique)
    sections["what_worked"] = ""
    sections["what_failed"] = ""
    sections["why_it_worked"] = ""
    sections["replicate"] = ""
    sections["avoid"] = ""
    sections["rewrite_suggestions"] = ""
    sections["thumbnail_fixes"] = ""
    sections["tag_suggestions"] = ""
    sections["final_blueprint"] = ""

    return sections


def assemble_report(sections, critique):
    lines = []
    lines.append(f"# SEO Critique: {critique.video_id}")
    lines.append("")
    lines.append(f"**Run ID:** {critique.analysis_run_id}")
    lines.append(f"**Scoring Version:** {critique.determinism.scoring_version}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Verdict")
    lines.append("")
    lines.append(sections["verdict"])
    lines.append("")
    lines.append("## Scorecard")
    lines.append("")
    lines.append(sections["scorecard"])
    lines.append("")
    lines.append("## Flags")
    lines.append("")
    lines.append(sections["flags"])
    lines.append("")

    prose_sections = [
        "what_worked", "what_failed", "why_it_worked", "replicate",
        "avoid", "rewrite_suggestions", "thumbnail_fixes",
        "tag_suggestions", "final_blueprint",
    ]
    prose_titles = [
        "What Worked", "What Failed", "Why It Probably Worked", "Replicate",
        "Avoid", "Rewrite Suggestions", "Thumbnail Fixes",
        "Tag Suggestions", "Final Blueprint",
    ]

    for section_key, title in zip(prose_sections, prose_titles):
        content = sections.get(section_key, "")
        if content:
            lines.append(f"## {title}")
            lines.append("")
            lines.append(content)
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by DivTube Intelligence Lab*")

    return "\n".join(lines)


def _render_verdict(critique):
    score = critique.overall_score
    if score >= 80:
        grade = "STRONG"
        summary = "The video package is well-optimized. Minor refinements may improve marginal metrics."
    elif score >= 60:
        grade = "HEALTHY"
        summary = "The video package is functional but has room for improvement in key areas."
    elif score >= 40:
        grade = "NEEDS WORK"
        summary = "The video package has notable weaknesses that limit discoverability and click-through."
    else:
        grade = "CRITICAL"
        summary = "The video package has critical weaknesses. Immediate revision recommended."

    return f"**Overall Score: {score}/100 ({grade})**\n\n{summary}"


def _render_scorecard(critique):
    lines = []
    lines.append("| Dimension | Score | Weight |")
    lines.append("|-----------|-------|--------|")

    dims = [
        ("Thumbnail Readability", "thumbnail", "25%"),
        ("Title Construction", "title", "30%"),
        ("Tag Clustering", "tag", "20%"),
        ("Performance", "performance", "25%"),
    ]

    for label, key, weight in dims:
        val = critique.scores.get(key)
        display = str(val) if val is not None else "N/A"
        lines.append(f"| {label} | {display} | {weight} |")

    lines.append(f"| **Overall** | **{critique.overall_score}** | |")
    rep = critique.scores.get("replicationValue", 0)
    lines.append(f"| Replication Value | {rep} | |")

    return "\n".join(lines)


def _render_flags(critique):
    if not critique.flags:
        return "No flags raised."

    lines = []
    for flag in critique.flags:
        icon = _SEVERITY_ICON.get(flag.severity, "?")
        lines.append(f"- [{icon}] **{flag.code}**: {flag.message}")
    return "\n".join(lines)
