export const PHOTONIC_ERROR_CODES = Object.freeze({
  PHOTONIC_UNKNOWN: 'PHOTONIC_UNKNOWN',

  // Packet validation
  PHOTONIC_PACKET_INVALID: 'PHOTONIC_PACKET_INVALID',
  PHOTONIC_DIMENSION_DEFAULTED: 'PHOTONIC_DIMENSION_DEFAULTED',
  PHOTONIC_DIMENSION_CLAMPED: 'PHOTONIC_DIMENSION_CLAMPED',
  PHOTONIC_STORAGE_DEFAULTED: 'PHOTONIC_STORAGE_DEFAULTED',

  // Simulator diagnostics
  PHOTONIC_ELECTRONIC_BOUNDARIES_PRESENT: 'PHOTONIC_ELECTRONIC_BOUNDARIES_PRESENT',
  PHOTONIC_DIAGNOSTIC_ONLY: 'PHOTONIC_DIAGNOSTIC_ONLY',
  PHOTONIC_LOW_COMPATIBILITY: 'PHOTONIC_LOW_COMPATIBILITY',

  // Bridge lifecycle
  PHOTONIC_BRIDGE_DISABLED: 'PHOTONIC_BRIDGE_DISABLED',
});

export const PHOTONIC_SEVERITIES = Object.freeze({
  ERROR: 'error',
  WARN: 'warn',
  INFO: 'info',
});
