export { VisualizerKit } from "./components/VisualizerKit";
export { ArcaneCard } from "./components/ArcaneCard";
export { OverlineLabel } from "./components/OverlineLabel";
export { TrackHero } from "./components/TrackHero";
export { AlbumArtifactTile } from "./components/AlbumArtifactTile";
export { MetadataMatrix } from "./components/MetadataMatrix";
export { ProvenanceCard } from "./components/ProvenanceCard";
export { CreditsCard } from "./components/CreditsCard";
export { LyricTracker } from "./components/LyricTracker";
export { VisualizerCore } from "./components/VisualizerCore";
export { FingerprintCard } from "./components/FingerprintCard";
export { CoordinatesCard } from "./components/CoordinatesCard";
export { SpectralAnalyzerCard } from "./components/SpectralAnalyzerCard";
export { SemanticMapCard } from "./components/SemanticMapCard";
export { EnergyMatrixCard } from "./components/EnergyMatrixCard";
export { CommerceCard } from "./components/CommerceCard";
export { PersistentPlayerBar } from "./components/PersistentPlayerBar";
export { WaveformScrubber } from "./components/WaveformScrubber";
export { IconButton } from "./components/IconButton";
export { FormatBadge } from "./components/FormatBadge";
export { SigilGlyph } from "./components/SigilGlyph";
export { RitualSyncCard } from "./components/RitualSyncCard";
export { VisualizerShell } from "./components/VisualizerShell";
export { ReleasePanel } from "./components/ReleasePanel";
export { BytecodePanel } from "./components/BytecodePanel";

export type { ScholomanceRelease, ScholomanceSigilSeed, ScholomanceSigilOutput, PlayerState } from "./types";
export { createSigilProfile } from "./utils/sigil";
export { scholomanceVisualizerComponents } from "./registry";
export { useLyricAlignment } from './hooks/useLyricAlignment';
export { parseAlignment, lineAtTime, wordAtTime } from './utils/lyricAlignment';
export type { LyricAlignment, AlignmentLine, AlignmentWord } from './utils/lyricAlignment';
