import React, { useEffect, useRef } from 'react';
import { combatBridge } from '../combatBridge.js';
import './GodotOverlay.css';

// 1920x1080 is the native resolution generated by the Godot exporters
const GODOT_WIDTH = 1920;
const GODOT_HEIGHT = 1080;

export default function GodotOverlay() {
  const canvasRef = useRef(null);
  const objectsMap = useRef(new Map());
  const activeTimeline = useRef(null);
  const animationFrameId = useRef(null);
  
  useEffect(() => {
    const handleSceneLoad = (sceneState) => {
      objectsMap.current.clear();
      activeTimeline.current = null;
      if (sceneState && sceneState.objects) {
        sceneState.objects.forEach(obj => {
          objectsMap.current.set(obj.id, { ...obj });
        });
      }
    };

    const handleSpellImpact = (timeline) => {
      activeTimeline.current = {
        timeline,
        startTime: performance.now(),
        lastProcessedFrame: -1
      };
    };

    combatBridge.on('godot_scene_load', handleSceneLoad);
    combatBridge.on('godot_spell_impact', handleSpellImpact);

    return () => {
      combatBridge.off('godot_scene_load', handleSceneLoad);
      combatBridge.off('godot_spell_impact', handleSpellImpact);
    };
  }, []);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const render = (time) => {
      const cw = canvas.width;
      const ch = canvas.height;
      
      const sx = cw / GODOT_WIDTH;
      const sy = ch / GODOT_HEIGHT;

      // 1. Process Timeline Updates
      if (activeTimeline.current) {
        const { timeline, startTime, lastProcessedFrame } = activeTimeline.current;
        const elapsedMs = time - startTime;
        const currentFrame = Math.floor((elapsedMs / 1000) * timeline.fps);

        if (currentFrame > lastProcessedFrame) {
          for (let f = lastProcessedFrame + 1; f <= currentFrame; f++) {
            const packet = timeline.frames.find(pkt => pkt.frame === f);
            if (packet) {
              packet.create?.forEach(c => {
                objectsMap.current.set(c.id, {
                  id: c.id,
                  type: c.type,
                  transform: { ...c.transform },
                  props: { ...c.props },
                  resource: c.resource,
                });
              });
              packet.update?.forEach(u => {
                const existing = objectsMap.current.get(u.id);
                if (existing) {
                  if (u.transform) Object.assign(existing.transform, u.transform);
                  if (u.props) Object.assign(existing.props, u.props);
                  if (u.visible !== undefined) existing.visible = u.visible;
                }
              });
              packet.destroy?.forEach(d => {
                objectsMap.current.delete(d.id);
              });
            }
          }
          activeTimeline.current.lastProcessedFrame = currentFrame;
          
          if (currentFrame >= timeline.durationFrames) {
            activeTimeline.current = null; // Timeline finished
          }
        }
      }

      ctx.clearRect(0, 0, cw, ch);

      // 2. Draw Objects
      // Sort by zIndex if it exists
      const objects = Array.from(objectsMap.current.values()).sort((a, b) => {
        const zA = a.transform?.zIndex || 0;
        const zB = b.transform?.zIndex || 0;
        return zA - zB;
      });

      objects.forEach(obj => {
        if (obj.visible === false) return;

        const { x, y, rotation = 0, scaleX = 1, scaleY = 1 } = obj.transform;
        const px = x * sx;
        const py = y * sy;

        ctx.save();
        ctx.translate(px, py);
        ctx.rotate(rotation);
        ctx.scale(scaleX, scaleY);

        // Proxy Rendering Logic based on resource or props
        const resource = obj.props?.resource || obj.resource;
        
        if (resource && resource.includes('obsidian_pillar')) {
          // Draw dark purple jagged rectangle
          ctx.fillStyle = '#0D0D1A';
          ctx.shadowColor = '#5a5a7a';
          ctx.shadowBlur = 10;
          ctx.fillRect(-30 * sx, -50 * sy, 60 * sx, 100 * sy);
        } 
        else if (resource && resource.includes('singularity')) {
          // Draw pulsing singularity
          const pulse = 1.0 + Math.sin(time / 200) * 0.1;
          ctx.scale(pulse, pulse);
          ctx.fillStyle = '#000000';
          ctx.shadowColor = '#00E5FF';
          ctx.shadowBlur = 20;
          ctx.beginPath();
          ctx.arc(0, 0, 40 * sx, 0, Math.PI * 2);
          ctx.fill();
        }
        else if (resource && resource.includes('amethyst_crack')) {
          // Draw purple diamond
          ctx.fillStyle = '#7B2FBE';
          ctx.beginPath();
          ctx.moveTo(0, -10 * sy);
          ctx.lineTo(10 * sx, 0);
          ctx.lineTo(0, 10 * sy);
          ctx.lineTo(-10 * sx, 0);
          ctx.fill();
        }
        else if (obj.type === 'AnimatedSprite2D' && obj.props?.fissure_width) {
          // Fissure curve
          ctx.strokeStyle = '#00E5FF';
          ctx.lineWidth = obj.props.fissure_width * 2 * sx;
          ctx.shadowColor = '#00E5FF';
          ctx.shadowBlur = 15;
          ctx.beginPath();
          ctx.moveTo(0, 0);
          ctx.lineTo(30 * sx, 0);
          ctx.stroke();
        }
        else if (obj.id.includes('void_shard') || obj.id.includes('burst')) {
          // Shard impact flash
          ctx.fillStyle = '#FFFFFF';
          ctx.shadowColor = '#00E5FF';
          ctx.shadowBlur = 15;
          ctx.beginPath();
          ctx.arc(0, 0, 15 * sx, 0, Math.PI * 2);
          ctx.fill();
        }

        ctx.restore();
      });

      animationFrameId.current = requestAnimationFrame(render);
    };

    animationFrameId.current = requestAnimationFrame(render);
    return () => cancelAnimationFrame(animationFrameId.current);
  }, []);

  return (
    <div className="godot-overlay-container">
      <canvas 
        ref={canvasRef} 
        width={800} 
        height={800} 
        className="godot-overlay-canvas"
      />
    </div>
  );
}
